# Generated by Django 4.0.6 on 2022-07-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published',
            new_name='add_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author_email',
            new_name='adoption',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='cost_first',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='imported',
        ),
        migrations.AddField(
            model_name='book',
            name='amortfirst_valid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Амортизация на начало периода'),
        ),
        migrations.AddField(
            model_name='book',
            name='cost_for',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость для вычисления амортизации'),
        ),
        migrations.AddField(
            model_name='book',
            name='costfinish_validone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Остаточная стоимость на начало периода'),
        ),
        migrations.AddField(
            model_name='book',
            name='costfirstvalid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость на начало периода'),
        ),
        migrations.AddField(
            model_name='book',
            name='finish_valid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость на конец периода'),
        ),
        migrations.AddField(
            model_name='book',
            name='number',
            field=models.IntegerField(default=False),
        ),
    ]
