# Generated by Django 4.0.6 on 2022-07-31 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_cost_for_book_calculate_depreciation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='add_date',
        ),
    ]
