# Generated by Django 4.0.6 on 2022-07-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_book_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='adoption',
            field=models.CharField(blank=True, max_length=75, verbose_name='Дата принятия к учету'),
        ),
        migrations.AlterField(
            model_name='book',
            name='calculate_depreciation',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость для вычисления амортизации'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cost_begining_period',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость на начало периода'),
        ),
        migrations.AlterField(
            model_name='book',
            name='depreciation_begining_period',
            field=models.FloatField(blank=True, null=True, verbose_name='Амортизация на начало периода'),
        ),
        migrations.AlterField(
            model_name='book',
            name='depreciation_end_period',
            field=models.FloatField(blank=True, null=True, verbose_name='Амортизация на конец периода'),
        ),
        migrations.AlterField(
            model_name='book',
            name='initial_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Первоначальная стоимость'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.CharField(default=False, max_length=100, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price_end_period',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость на конец периода'),
        ),
        migrations.AlterField(
            model_name='book',
            name='residual_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Остаточная стоимость'),
        ),
        migrations.AlterField(
            model_name='book',
            name='residual_value_begining',
            field=models.FloatField(blank=True, null=True, verbose_name='Остаточная стоимость на начало периода'),
        ),
    ]
